version = 1

test_patterns = ["**/*_test.go"]

exclude_patterns = [
  "**/*_mock.go",
  "**/*_pb.go",
  "**/*_grpc.pb.go",
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Lynicis/go-rest-api-boilerplate"