run:
  concurrency: 4
  timeout: 3m
  go: "1.18"

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gomodguard
    - cyclop
    - gocritic
    - goconst
    - whitespace
    - varcheck
    - varnamelen
    - funlen
    - goimports
    - lll
    - gosec

severity:
  default-severity: error

issues:
  exclude:
    - _test\.go
    - _grpc\.pb\.go
    - \.pb\.go