repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-beta.5
    hooks:
      - id: golangci-lint-mod
      - id: my-cmd-mod
        name: unit test
        alias: unit test
        args: [make, test]