repos:
  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: v1.0.0-rc.1
    hooks:
      - id: golangci-lint

      - id: my-cmd-mod
        name: unit test
        alias: unit test
        args: [make, test]

      - id: go-sec-repo-pkg