name: "go-cache"
description: "go installing with cache"
runs:
  using: composite
  steps:
    - name: Set up Go with cache
      uses: magnetikonline/action-golang-cache@v2
      with:
        go-version: 1.18