name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions@checkout@v2

      - uses: lynicis/go-rest-api-boilerplate/.github/actions/go-cache/go-cache.yaml

      - name: Linting
        run: go fmt ./...

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: lynicis/go-rest-api-boilerplate/.github/actions/go-cache/go-cache.yaml

      - name: Build
        run: go build ./...

  unit-test:
    needs:
      - build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: lynicis/go-rest-api-boilerplate/.github/actions/go-cache/go-cache.yaml

      - name: Test
        run: go test -tags=unit ./...