name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: 1.17.8

      - name: Build
        run: go build ./...

  unit-test:
    needs:
      - build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: magnetikonline/action-golang-cache@v2
        with:
          go-version: 1.17.8

      - name: Test
        run: go test -tags=unit ./...