name: CI/CD

on:
  push:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - name: Linting
        run: go fmt ./...

  build:
    needs:
      - lint

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - name: Build
        run: go build ./...

  unit-test:
    needs:
      - build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - name: Test
        run: go test -tags=unit ./...

  coverage:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - name: Generate coverage report
        run: go test -tags=unit -coverprofile=coverage.txt -covermode=atomic ./...

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_SECRET_KEY }}
          files: ./coverage.txt
          fail_ci_if_error: true

  security-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - uses: deepsourcelabs/test-coverage-action@master
        with:
          key: go
          coverage-file: coverage.txt
          fail-ci-on-error: false
          dsn: ${{ secrets.DEEPSOURCE_DSN }}