name: CI/CD

on:
  push:
    branches:
      - master

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - name: Linting
        run: go fmt ./...

  build:
    needs:
      - lint

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - name: Build
        run: go build ./...

  unit-test:
    needs:
      - build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - name: Test
        run: go test -tags=unit ./...

  coverage:
    needs:
      - unit-test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/go-cache

      - name: Generate coverage report
        run: |
          - go install github.com/jstemmer/go-junit-report@latest
          - go test -tags=unit ./... | go-junit-report > report.xml

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_SECRET_KEY }}
          files: ./report.xml
          fail_ci_if_error: true
          flags: unit