name: CI

on:
  push:
    branches:
      - master

env:
  APP_NAME: ${{ github.event.repository.name }}
  CONTAINER_REGISTRY_TOKEN: ${{ secrets.GHCR_TOKEN }}

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/go-cache

      - name: Linting
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  build:
    needs:
      - lint

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/go-cache

      - name: Build
        shell: bash
        run: go build -o $APP_NAME ./cmd/**

      - name: Upload executable file as artifact
        uses: actions/upload-artifact@v3
        with:
          path: $APP_NAME
          if-no-files-found: error

  dockerize:
    needs:
      - build

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Download executable file
        uses: actions/download-artifact@v3
        with:
          name: $APP_NAME

      - name: Build Docker image
        shell: bash
        run: docker build . --tag $APP_NAME

      - name: Login to container registry
        shell: bash
        run: docker login ghcr.io -u $ --password-stdin

      - name: Push image to container registry
        shell: bash
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$APP_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $APP_NAME $IMAGE_ID
          docker push $IMAGE_ID

  unit-test:
    needs:
      - dockerize

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/go-cache

      - name: Run tests
        run: go test -tags=unit ./...

  coverage:
    needs:
      - unit-test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/go-cache

      - name: Generate coverage report
        shell: bash
        run: go test -tags=unit -coverprofile=coverage.out -covermode=atomic ./...

      - name: Static code analysis
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
