name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:

  quality-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World!"

