name: CI

on:
  push:
    branches:
      - master

    tags:
      - v*

env:
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2

      - uses: actions/checkout@v3

      - name: Linting
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest

  build:
    needs:
      - lint

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/go-cache

      - name: Build
        run: go build ./...

  dockerize:
    needs:
      - build

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Build image
        run: |
          docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

  unit-test:
    needs:
      - dockerize

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/go-cache

      - name: Test
        run: go test -tags=unit ./...

  analysis:
    needs:
      - unit-test

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/actions/go-cache

      - name: Generate coverage report
        run: go test -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Measure test coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_SECRET_KEY }}
          files: ./coverage.txt
          fail_ci_if_error: true

      - name: Static code analysis
        uses: deepsourcelabs/test-coverage-action@master
        with:
          key: go
          coverage-file: coverage.txt
          fail-ci-on-error: true
          dsn: ${{ secrets.DEEPSOURCE_DSN }}

  security-check:
    needs:
      - analysis

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: '-no-fail -fmt sarif -out results.sarif ./...'

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
