name: CD

on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: |
          echo "Hello World!"

